### ISSUE TITLE
Set up some kind of system to build against the latest nightly regularly.

### ISSUE THREAD

**Issue by ibabushkin** [ibabushkin/rust-semverver#33]
In times when I'm not working on the project daily, it can take me some time to notice a nightly breaks the build. This needs fixing (not necessarily in this repo, however).

**Comment by cuviper** [comment]
You could just enable a cron job (daily/weekly/monthly) in Travis CI settings.

**Comment by ibabushkin** [comment]
Done! I didn't know that's an option, thanks for pointing it out @cuviper.
