### ISSUE TITLE
tweak the compiler to assign new spans to `use` directives

### ISSUE THREAD

**Issue by ibabushkin** [ibabushkin/rust-semverver#7]
This would help us in some cases to output more helpful spans. However, this depends on #5.

**Comment by eddyb** [comment]
Note: the compiler has `Span`s for `use` items within the same crate, but the export map (which is what gets serialized, not the `use` items) *loses* the export chain completely.

You'd only be interested in the `use` that brought the item into the module, not the rest of the chain, which means you only need to add an extra `Span` to each re-export, I believe.

**Comment by ibabushkin** [comment]
The underlying issue is solved now, so I'm closing this.
